export type ToolMeta = {
  toolKey: string;
  title: string;
  description: string;
  href: string;
  badge: string;
  category: string;
  mode: 'text' | 'file' | 'dual' | 'generate';
  placeholder: string;
  premium?: boolean;
};

export const toolList: ToolMeta[] = [
  {
    toolKey: 'pdf-convert',
    title: 'PDF 转换',
    description: '支持 PDF 文件占位转换，后续可扩展为 PDF 转 Word、图片、文本等功能。',
    href: '/tools/pdf-convert',
    badge: '文件工具',
    category: '文件工具',
    mode: 'file',
    placeholder: '上传 PDF 后可将文件转换为多种格式，适合文档工具流量页。',
  },
  {
    toolKey: 'json-format',
    title: 'JSON 格式化',
    description: '快速美化和校验 JSON 文本，适合开发者和 SEO 内容处理。',
    href: '/tools/json-format',
    badge: '开发工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '粘贴或输入 JSON 文本，快速执行格式化和语法检测。',
  },
  {
    toolKey: 'word-count',
    title: '字数统计',
    description: '支持中文和英文统计，适合文章、文案和内容优化。',
    href: '/tools/word-count',
    badge: '内容工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入文章内容即可获得字符、单词、段落和阅读时间统计。',
  },
  {
    toolKey: 'image-compress',
    title: '图片压缩占位',
    description: '为站点预留图片压缩能力，后续可扩展为在线压缩体验。',
    href: '/tools/image-compress',
    badge: '图片工具',
    category: '图片工具',
    mode: 'file',
    placeholder: '上传图片并查看压缩预估，用于构建图片优化与广告变现页面。',
  },
  {
    toolKey: 'base64',
    title: 'Base64 编码',
    description: '进行文本 Base64 编码和解码，适合数据处理与 URL 安全传输。',
    href: '/tools/base64',
    badge: '编码工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '支持文本的 Base64 编码与解码，方便数据处理与调试。',
  },
  {
    toolKey: 'timestamp',
    title: '时间戳转换',
    description: '在 Unix 时间戳与可读日期之间快速转换，适合开发与日志分析。',
    href: '/tools/timestamp',
    badge: '时间工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '输入时间戳或日期，快速获取对应的格式化时间结果。',
  },
  {
    toolKey: 'url-encode',
    title: 'URL 编码',
    description: '对 URL 参数进行编码与解码，方便构建安全的查询字符串。',
    href: '/tools/url-encode',
    badge: '开发工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '快速进行 URL 参数编码与解码，保障链接传输安全性。',
  },
  {
    toolKey: 'password-generator',
    title: '密码生成',
    description: '生成安全随机密码，支持长度、大小写和特殊字符配置。',
    href: '/tools/password-generator',
    badge: '安全工具',
    category: '工具',
    mode: 'generate',
    placeholder: '通过参数生成高强度密码，适合作为账号安全工具页面。',
  },
  {
    toolKey: 'color-convert',
    title: '颜色代码转换',
    description: '在 HEX 和 RGB 颜色代码之间互相转换，适合设计与前端配色。',
    href: '/tools/color-convert',
    badge: '设计工具',
    category: '设计工具',
    mode: 'text',
    placeholder: '输入颜色代码即可转换格式，适合视觉设计与前端样式工具。',
  },
  {
    toolKey: 'markdown-html',
    title: 'Markdown 转 HTML',
    description: '将 Markdown 文本转换为 HTML，适合内容编辑与文档发布。',
    href: '/tools/markdown-html',
    badge: '内容工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '将 Markdown 文本转换为 HTML 代码，方便文档发布与网页编辑。',
  },
  {
    toolKey: 'keyword-extract',
    title: '关键词提取',
    description: '从文本中提取核心关键词并统计密度，适合文章优化与广告投放。',
    href: '/tools/keyword-extract',
    badge: 'SEO 工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入内容后提取高频词，帮助您进行关键词分析与标题优化。',
    premium: true,
  },
  {
    toolKey: 'seo-title-generator',
    title: 'SEO 标题生成',
    description: '根据内容自动生成 SEO 优化标题，适合营销页面与内容编辑。',
    href: '/tools/seo-title-generator',
    badge: 'SEO 工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入文章或页面摘要，快速生成符合搜索引擎的优化标题。',
    premium: true,
  },
  {
    toolKey: 'text-translate',
    title: '内容翻译助手',
    description: '将文本翻译为目标语言，适合跨境内容与付费翻译入口。',
    href: '/tools/text-translate',
    badge: '翻译工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入文本后快速翻译成英文或中文，前半年会员免费。',
    premium: true,
  },
  {
    toolKey: 'copywriting-polish',
    title: '文案润色',
    description: '优化广告文案或标题，适合营销推广与内容付费服务。',
    href: '/tools/copywriting-polish',
    badge: '文案工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入营销文案，获取更简洁清晰的优化建议。',
    premium: true,
  },
  {
    toolKey: 'content-summarizer',
    title: '文章摘要生成',
    description: '从长文本中提取核心摘要，适合内容归纳和付费内容入口。',
    href: '/tools/content-summarizer',
    badge: '内容工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入文章或页面内容，快速生成简明摘要。',
    premium: true,
  },
  {
    toolKey: 'text-diff',
    title: '文本差异比较',
    description: '对比两个文本版本，快速定位差异，适合文案校对和代码比较。',
    href: '/tools/text-diff',
    badge: '对比工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '对比两个文本内容，快速显示差异，适合校对与编辑。',
  },
  {
    toolKey: 'text-case',
    title: '大小写转换',
    description: '将文本转换为大写、首字母大写或小写，适合文案处理。',
    href: '/tools/text-case',
    badge: '内容工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '快速转换文本大小写，便于文案格式统一与内容润色。',
  },
  {
    toolKey: 'lorem-ipsum',
    title: 'Lorem Ipsum 生成',
    description: '快速生成占位 Lorem Ipsum 文本，方便页面设计和内容布局。',
    href: '/tools/lorem-ipsum',
    badge: '占位工具',
    category: '内容工具',
    mode: 'generate',
    placeholder: '生成占位文本内容，帮助页面设计和布局演示。',
  },
  {
    toolKey: 'html-compress',
    title: 'HTML 压缩',
    description: '压缩 HTML 代码，移除多余空白和注释，提升加载性能。',
    href: '/tools/html-compress',
    badge: '前端工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '对 HTML 源码进行压缩，减少大小并提高加载效率。',
  },
  {
    toolKey: 'qr-code',
    title: 'QR 码生成',
    description: '生成二维码文本占位，适合移动设备扫描和链接分享。',
    href: '/tools/qr-code',
    badge: '移动工具',
    category: '站长工具',
    mode: 'generate',
    placeholder: '输出二维码占位，适合链接分享与扫码体验页面。',
  },
];

export const toolMap = new Map(toolList.map((tool) => [tool.toolKey, tool]));
