export type ToolMeta = {
  toolKey: string;
  title: string;
  description: string;
  href: string;
  badge: string;
  category: string;
  mode: 'text' | 'file' | 'dual' | 'generate';
  placeholder: string;
  premium?: boolean;
};

export const toolList: ToolMeta[] = [
  {
    toolKey: 'pdf-convert',
    title: '万能文档转换',
    description: '支持 PDF、Word、Excel、PPT、TXT、Markdown、HTML 与图片常用格式互转，优先浏览器本地处理；PDF 解析失败时启用兼容转换。',
    href: '/tools/pdf-convert',
    badge: '文件工具',
    category: '文件工具',
    mode: 'file',
    placeholder: '选择源文件和目标格式，转换完成后可复制预览并下载真实结果文件。',
  },
  {
    toolKey: 'json-format',
    title: 'JSON 格式化',
    description: '快速美化和校验 JSON 文本，适合开发者和 SEO 内容处理。',
    href: '/tools/json-format',
    badge: '开发工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '粘贴或输入 JSON 文本，快速执行格式化和语法检测。',
  },
  {
    toolKey: 'word-count',
    title: '字数统计',
    description: '支持中文和英文统计，适合文章、文案和内容优化。',
    href: '/tools/word-count',
    badge: '内容工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入文章内容即可获得字符、单词、段落和阅读时间统计。',
  },
  {
    toolKey: 'image-compress',
    title: '图片压缩',
    description: '在浏览器中压缩 JPG、PNG 等常见图片，并下载体积更小的 WebP 文件。',
    href: '/tools/image-compress',
    badge: '图片工具',
    category: '图片工具',
    mode: 'file',
    placeholder: '上传图片后在本地压缩为 WebP，处理完成即可下载，不上传原始图片。',
  },
  {
    toolKey: 'base64',
    title: 'Base64 编码',
    description: '进行文本 Base64 编码和解码，适合数据处理与 URL 安全传输。',
    href: '/tools/base64',
    badge: '编码工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '支持文本的 Base64 编码与解码，方便数据处理与调试。',
  },
  {
    toolKey: 'timestamp',
    title: '时间戳转换',
    description: '在 Unix 时间戳与可读日期之间快速转换，适合开发与日志分析。',
    href: '/tools/timestamp',
    badge: '时间工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '输入时间戳或日期，快速获取对应的格式化时间结果。',
  },
  {
    toolKey: 'url-encode',
    title: 'URL 编码',
    description: '对 URL 参数进行编码与解码，方便构建安全的查询字符串。',
    href: '/tools/url-encode',
    badge: '开发工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '快速进行 URL 参数编码与解码，保障链接传输安全性。',
  },
  {
    toolKey: 'password-generator',
    title: '密码生成',
    description: '生成安全随机密码，支持长度、大小写和特殊字符配置。',
    href: '/tools/password-generator',
    badge: '安全工具',
    category: '工具',
    mode: 'generate',
    placeholder: '通过参数生成高强度密码，适合作为账号安全工具页面。',
  },
  {
    toolKey: 'color-convert',
    title: '颜色代码转换',
    description: '在 HEX 和 RGB 颜色代码之间互相转换，适合设计与前端配色。',
    href: '/tools/color-convert',
    badge: '设计工具',
    category: '设计工具',
    mode: 'text',
    placeholder: '输入颜色代码即可转换格式，适合视觉设计与前端样式工具。',
  },
  {
    toolKey: 'markdown-html',
    title: 'Markdown 转 HTML',
    description: '将 Markdown 文本转换为 HTML，适合内容编辑与文档发布。',
    href: '/tools/markdown-html',
    badge: '内容工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '将 Markdown 文本转换为 HTML 代码，方便文档发布与网页编辑。',
  },
  {
    toolKey: 'keyword-extract',
    title: '关键词提取',
    description: '从文本中提取核心关键词并统计密度，适合文章优化与广告投放。',
    href: '/tools/keyword-extract',
    badge: 'SEO 工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入内容后提取高频词，帮助您进行关键词分析与标题优化。',
  },
  {
    toolKey: 'seo-title-generator',
    title: 'SEO 标题生成',
    description: '根据内容自动生成 SEO 优化标题，适合营销页面与内容编辑。',
    href: '/tools/seo-title-generator',
    badge: 'SEO 工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入文章或页面摘要，快速生成符合搜索引擎的优化标题。',
  },
  {
    toolKey: 'text-translate',
    title: '内容翻译助手',
    description: '将文本翻译为目标语言，适合跨境内容与中英文沟通。',
    href: '/tools/text-translate',
    badge: '翻译工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入文本后快速翻译成英文或中文，新账号提供 180 天在线翻译体验。',
    premium: true,
  },
  {
    toolKey: 'copywriting-polish',
    title: '文案润色',
    description: '优化广告文案或标题，适合营销推广与内容编辑。',
    href: '/tools/copywriting-polish',
    badge: '文案工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入营销文案，获取更简洁清晰的优化建议。',
  },
  {
    toolKey: 'content-summarizer',
    title: '文章摘要生成',
    description: '从长文本中提取核心摘要，适合内容归纳与快速阅读。',
    href: '/tools/content-summarizer',
    badge: '内容工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '输入文章或页面内容，快速生成简明摘要。',
  },
  {
    toolKey: 'text-diff',
    title: '文本差异比较',
    description: '对比两个文本版本，快速定位差异，适合文案校对和代码比较。',
    href: '/tools/text-diff',
    badge: '对比工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '对比两个文本内容，快速显示差异，适合校对与编辑。',
  },
  {
    toolKey: 'text-case',
    title: '大小写转换',
    description: '将文本转换为大写、首字母大写或小写，适合文案处理。',
    href: '/tools/text-case',
    badge: '内容工具',
    category: '内容工具',
    mode: 'text',
    placeholder: '快速转换文本大小写，便于文案格式统一与内容润色。',
  },
  {
    toolKey: 'lorem-ipsum',
    title: 'Lorem Ipsum 生成',
    description: '快速生成占位 Lorem Ipsum 文本，方便页面设计和内容布局。',
    href: '/tools/lorem-ipsum',
    badge: '占位工具',
    category: '内容工具',
    mode: 'generate',
    placeholder: '生成占位文本内容，帮助页面设计和布局演示。',
  },
  {
    toolKey: 'html-compress',
    title: 'HTML 压缩',
    description: '压缩 HTML 代码，移除多余空白和注释，提升加载性能。',
    href: '/tools/html-compress',
    badge: '前端工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '对 HTML 源码进行压缩，减少大小并提高加载效率。',
  },
  {
    toolKey: 'qr-code',
    title: 'QR 码生成',
    description: '将文本或网址生成可扫描的二维码，并支持下载 PNG 图片。',
    href: '/tools/qr-code',
    badge: '移动工具',
    category: '站长工具',
    mode: 'generate',
    placeholder: '输入文本或网址，生成二维码后可复制内容或下载 PNG 图片。',
  },
  {
    toolKey: 'json-csv',
    title: 'JSON CSV 互转',
    description: '在 JSON 对象数组与 CSV 表格之间双向转换，适合数据导入、运营表格和接口调试。',
    href: '/tools/json-csv',
    badge: '数据工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '输入 JSON 数组或 CSV 表格内容，选择转换方向后生成可下载结果。',
  },
  {
    toolKey: 'yaml-json',
    title: 'YAML JSON 互转',
    description: '将 YAML 配置与 JSON 数据双向转换并校验语法，适合开发、运维和配置迁移。',
    href: '/tools/yaml-json',
    badge: '配置工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '粘贴 YAML 或 JSON 配置，选择转换方向后生成规范结果。',
  },
  {
    toolKey: 'uuid-generator',
    title: 'UUID 批量生成',
    description: '使用浏览器安全随机源批量生成标准 UUID v4，适合数据库主键、测试数据和接口开发。',
    href: '/tools/uuid-generator',
    badge: '开发工具',
    category: '开发工具',
    mode: 'generate',
    placeholder: '输入生成数量，一次生成 1 至 100 个 UUID v4。',
  },
  {
    toolKey: 'jwt-decoder',
    title: 'JWT 解码器',
    description: '本地解码 JWT Header、Payload、过期时间与签名部分，不上传令牌。',
    href: '/tools/jwt-decoder',
    badge: '安全工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '粘贴 JWT 令牌以查看结构；本工具只解码，不验证签名真实性。',
  },
  {
    toolKey: 'regex-tester',
    title: '正则表达式测试',
    description: '实时测试正则表达式，显示匹配内容、索引和捕获分组，适合开发与数据清洗。',
    href: '/tools/regex-tester',
    badge: '开发工具',
    category: '开发工具',
    mode: 'dual',
    placeholder: '输入正则表达式与待测试文本，例如 /tool(ly)?/gi。',
  },
  {
    toolKey: 'hash-generator',
    title: 'SHA 哈希生成',
    description: '在本地生成 SHA-256 或 SHA-512 哈希，适合内容校验、签名准备和开发调试。',
    href: '/tools/hash-generator',
    badge: '安全工具',
    category: '开发工具',
    mode: 'text',
    placeholder: '输入任意文本并选择 SHA-256 或 SHA-512，立即生成十六进制摘要。',
  },
  {
    toolKey: 'rmb-uppercase',
    title: '人民币金额大写',
    description: '将数字金额转换为规范中文人民币大写，适合合同、报销单、收据和财务填写。',
    href: '/tools/rmb-uppercase',
    badge: '中文工具',
    category: '办公工具',
    mode: 'text',
    placeholder: '输入数字金额，例如 123456.78，生成“人民币壹拾贰万…”格式。',
  },
  {
    toolKey: 'image-convert',
    title: '图片格式转换',
    description: '在 JPG、PNG、WebP 之间转换图片格式并控制质量，处理后直接下载。',
    href: '/tools/image-convert',
    badge: '图片工具',
    category: '图片工具',
    mode: 'file',
    placeholder: '上传 JPG、PNG 或 WebP，选择目标格式后在本地生成新图片。',
  },
];

export const toolMap = new Map(toolList.map((tool) => [tool.toolKey, tool]));
